services:
  # Auth service
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    environment:
      - PORT=3002
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=challenge_db
    ports:
      - 3002:3002
    networks:
      - challenge-network
    depends_on:
      - db
    command: sh -c "pnpm migration:run:prod && pnpm start:prod"

  # Task service
  task-service:
    container_name: task-service
    build:
      context: .
      dockerfile: ./apps/task-service/Dockerfile
    ports:
      - 3003:3003
    environment:
      - PORT=3003
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=challenge_db
    networks:
      - challenge-network
    depends_on:
      - db
    command: sh -c "pnpm migration:run:prod && pnpm start:prod"

  # API Gateway
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - AUTH_SERVICE_URL=http://auth-service:3002
      - TASK_SERVICE_URL=http://task-service:3003
    networks:
      - challenge-network
    depends_on:
      - db
      - auth-service
      - task-service

  # Notification service
  notifications-service:
    container_name: notifications-service
    build:
      context: .
      dockerfile: ./apps/notifications-service/Dockerfile
    ports:
      - 3004:3004
    environment:
      - PORT=3004
    networks:
      - challenge-network
    depends_on:
      - db
      - auth-service
      - task-service

  # Front end
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        # use rota relativa; o nginx faz o proxy
        VITE_API_URL: "http://192.168.1.19:3001"
        VITE_APP_NAME: "TaskIntelligence"
        VITE_APP_ENVIRONMENT: "production"
        VITE_WS_URL: "http://192.168.1.19:3001"
        VITE_WS_PATH: "/ws"
    ports:
      - "3000:3000"
    networks:
      - challenge-network
    environment:
      - PORT=3000
    depends_on:
      - api-gateway

  # Postgres
  db:
    image: postgres:17.5-alpine3.21
    container_name: db
    attach: false
    ports:
      - "5432:5432"
    networks:
      - challenge-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: challenge_db

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    attach: false
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - challenge-network
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes: [rabbitmq_data:/var/lib/rabbitmq']
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  challenge-network:
    driver: bridge
